from LDA.lda import *


doc1 = 'I’m so upset!! I don’t even know where to begin!\n\n\nTo start off, I think I completely failed my geometry quiz, which I know I should’ve studied more for...my dad’s not gonna be happy about that. :( Then, we had a pop quiz in history on the reading homework from last night, and I completely forgot most of what I read, which made me even more upset because I actually did the reading! But what really made me mad was the note that Sarah slipped into my locker during passing period. She said she was sad that I’ve been hanging out with Jane more lately and thinks that I don’t want to be her friend anymore. I can’t believe she thinks that, especially after talking with her on the phone for hours and hours last month while she was going through her breakup with Nick! Just because I’ve been hanging out with Jane a little more than usual doesn’t mean I’m not her friend anymore. She completely blew me off at lunch, and when I told Jane, she thought that Sarah was being a “drama queen.”\n\n\nhis is just what I need! My parents are getting on my case about doing more extracurricular activities, I have a huge paper due for AP English soon, and I can’t understand a thing in advanced Spanish! The last thing I need is for my best friend to think I hate her and barely text me back anymore.\n\n\nUggh! I can’t concentrate on anything right now because of it. I hope she gets over it!!!'
doc2 = 'Today was a little better. I texted Sarah last night asking if she wanted to have lunch with me today, just the two of us, and she said sure. I told her that just because I’m hanging out with Jane, it doesn’t change anything about our friendship. After all, we’ve been friends since first grade! She said that she knows that, but she just felt like the third wheel because she doesn’t think that Jane likes her and because Jane and I have a lot of classes together. I told her not to worry about what Jane thought and that I’d talk to her about it. Sarah felt a lot better, and after we both cried a little, we spent the rest of lunch catching up on the latest gossip, which I missed! During English, I talked to Jane about what Sarah said. She said that it’s not that she doesn’t like Sarah; she just thinks that she gets too worked up about things sometime, like her breakup with Nick. I explained why Sarah was so upset about it and how Nick had cheated on her, which Jane didn’t know, and she felt bad for saying mean things about Sarah. I think Jane’s really cool, but I wish she wouldn’t assume things about people. I’m worried she was saying mean things about Sarah to our other friends when she didn’t know the truth. She sometimes likes to spread rumors even when she doesn’t know if they’re true.   I thought it would be fun for the three of us to get some coffee after school and try to make everything better. I’m not sure how well that worked, because even though Jane was trying really hard to be nice to Sarah, I could tell that Sarah was being really fake with Jane. When I texted Sarah later, she said everything was fine, but I know her well enough to know that’s not completely true. ::Sigh:: Oh well. I’m not her mom, and I can’t force her to feel anything. It just frustrates me because I don’t want things to change between us... We’ll see what happens. I have to get some math homework done now!'
doc3 = 'Sorry I didn’t get to write last night! It was such a busy day, and I was too tired to write anything...I was right about Sarah not being okay. Yesterday, she barely spoke to me, and anything she did say was a “yes” or “no” answer.  I tried so hard to get her to cheer up, but of course she just kept saying, “I’m fine, I’m fine.” Uggh! I wish she would just be honest with me! I’m always honest with her! It’s not fair!Jane also seemed mad all day because she could tell that Sarah was being fake nice to her. I hate being in the middle of all of this. What am I supposed to do? Sarah’s been my friend since forever, and Jane is my new friend, and I don’t want to hurt anyone’s feelings! But I think that Jane is right about Sarah. I think Sarah sometimes gets too dramatic about things. She’s being kind of a brat about all of this, but I don’t want to tell her that to her face, she’d never forgive me.I wish things were simple like they were in elementary school.'

docs = [doc1,doc2,doc3]

lda_model(docs,6)